default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['USERPASS'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: catalog_dev

test:
  <<: *default
  database: catalog_test

production:
  <<: *default
  database: catalog